### ISSUE TITLE
Need to reload_all before being able to search for the "purple" modules

### ISSUE THREAD

**Issue by imbaray** [praetorian-inc/purple-team-attack-automation#3]

**Comment by daniel-infosec** [comment]
I was able to replicate but I'm not sure of the best fix yet. We could update the documentation, but I think there's a setting somewhere to automatically load those paths. I'll look into it.

**Comment by daniel-infosec** [comment]
Updated the docs for now I'll keep this open since this should be automatable

**Comment by tmsteen** [comment]
Going to test if adding it to https://github.com/praetorian-code/purple-team-attack-automation/blob/master/docker/msfconsole.rc since that gets loaded when the container is spun up. 

Will report back.
