### ISSUE TITLE
Issue with FROM ruby:2.6.2-alpine3.9 AS builder - RHEL 7.4

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [praetorian-inc/purple-team-attack-automation#4]
## Steps to reproduce
while running ``` docker-compose build ``` get following error:
```
Step 1/35 : FROM ruby:2.6.2-alpine3.9 AS builder
ERROR: Service 'ms' failed to build: Error parsing reference: "ruby:2.6.2-alpine3.9 AS builder" is not a valid repository/tag: invalid reference format
```

## Expected behavior

What should happen?

## Current behavior

What happens instead?
build fails

### OS
RHEL 7.4
Using docker EE 

> this may be the issue?

**Comment by daniel-infosec** [comment]
Going to try to repo to see if its a RHEL or docker EE issue

**Comment by daniel-infosec** [comment]
I don't currently have access to docker EE. Can you give the updated instructions here https://github.com/praetorian-code/purple-team-attack-automation/wiki/Installation a try and let me know @lostInSpaceSomewhere ?

**Comment by lostInSpaceSomewhere** [comment]
@daniel-infosec  
think i know what the issue is here.
docker version of 1.17.5 + fixes the issues.
from what my linux guys are telling me its not avialable in RHEL docker-ee yet. :(.  Im looking for a workaround.  Saw somewher if i use -tag paramenter in the docker-compose build it may help.  testing.

**Comment by daniel-infosec** [comment]
Marking as closed unless there's further updates
